### DISCUSSION TITLE
Toast hide animation squishing the toast into vertical line

### DISCUSSION THREAD

**Discussion by hackel** [cdmoro/bootstrap-vue-3#2215] [Q&A]
In my project, whenever I show a (top-center) toast, it initially displays fine, but when it hides, it gets squished into a tall vertical line before it shifts left and fades out.  I tried to capture a screenshot of what I mean.  You can see the title "Broker Dashboard" at the top, and the green body of the toast is extremely faint going all the way down the page.

![image](https://github.com/user-attachments/assets/3f4a2f06-2a86-444f-82c0-aa9106c2201e)

This works fine on Stackblitz, so I know I must have some conflicting CSS in my project *somewhere*, but I've had no luck in identifying it.  Does anyone have any idea what might be causing this?

**Comment by Hiws** [comment]
A caveman way i usually debug transitions with, is just by slowing it down.
You can add this CSS to slow the leave transition of the toast down.

Should give you time to inspect the toast DOM and CSS to see what might be causing the shift.

```css
.b-list-leave-active {
  transition: all 60s cubic-bezier(0.55, 0, 0.1, 1);
}
```

**Reply by hackel** [reply]
Thank you for this advice!  I reduced my app to a single empty component and stripped out all the custom CSS, but it still didn't fix it.  Finally, just playing around, I came across this simple solution that seems to be doing the trick:
```css
.toast.b-list-leave-active {
    min-width: $toast-max-width;
}
```
This still doesn't feel right, but I'm going with it for now!
